
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
    #static-path-pattern: /static/**
  resources:
    add-mappings: false

mybatis:
   mapper-locations: classpath:mybatis/mapper/*.xml
   type-aliases-package: com.dingzan.domain;com.dingzan.system.domain

#page helper
pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: pageNum=pageNum;pageSize=pageSize;

#shiro redis 
sys:
  shiro:
    redis: false
    
#log
logging:
   #config: classpath:logback-boot.xml
   level:
     root: info
     org.mybatis: info
     com.dingzan: debug
     
#允许访问监控点信息
#management.security.enabled: false  
